using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BlazingSpire.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class PlaygroundGenerator : IIncrementalGenerator
{
    private const string BaseClassName = "BlazingSpireComponentBase";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Use compilation to find all types inheriting from BlazingSpireComponentBase.
        // We can't rely on BaseList syntax because Blazor components get their base class
        // from @inherits in .razor files, which the Razor generator merges into the type.
        var compilationProvider = context.CompilationProvider;

        context.RegisterSourceOutput(compilationProvider, GenerateSource);
    }

    private static void GenerateSource(SourceProductionContext context, Compilation compilation)
    {
        var components = new List<ComponentInfo>();

        foreach (var tree in compilation.SyntaxTrees)
        {
            var model = compilation.GetSemanticModel(tree);
            var root = tree.GetRoot();

            foreach (var classDecl in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
            {
                if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
                    continue;

                if (symbol.IsAbstract || !symbol.CanBeReferencedByName)
                    continue;

                if (!InheritsFrom(symbol, BaseClassName))
                    continue;

                // Skip generic open types
                if (symbol.IsGenericType)
                    continue;

                // Skip sub-components with required CascadingParameter
                if (HasRequiredCascadingParameter(symbol))
                    continue;

                // Skip if marked [Browsable(false)]
                if (HasBrowsableFalse(symbol))
                    continue;

                var ns = symbol.ContainingNamespace.ToDisplayString();
                var name = symbol.Name;
                var fullName = $"{ns}.{name}";

                // Deduplicate (partial classes appear in multiple syntax trees)
                if (components.All(c => c.FullName != fullName))
                {
                    components.Add(new ComponentInfo(name, ns, fullName));
                }
            }
        }

        if (components.Count == 0)
            return;

        var sorted = components.OrderBy(c => c.Name).ToList();
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Components;");
        sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        var namespaces = sorted.Select(c => c.Namespace).Distinct().OrderBy(n => n);
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace BlazingSpire.Demo.Components.Demo;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated render factories for the component playground.");
        sb.AppendLine("/// Each factory uses a closed generic OpenComponent to survive trimming.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class PlaygroundFactories");
        sb.AppendLine("{");

        // Registry: name → factory
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, System.Func<IReadOnlyDictionary<string, object?>, RenderFragment>> All = new Dictionary<string, System.Func<IReadOnlyDictionary<string, object?>, RenderFragment>>");
        sb.AppendLine("    {");
        foreach (var c in sorted)
        {
            sb.AppendLine($"        [\"{c.Name}\"] = Render{c.Name},");
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        // Individual render methods
        foreach (var c in sorted)
        {
            sb.AppendLine($"    public static RenderFragment Render{c.Name}(IReadOnlyDictionary<string, object?> parameters) => builder =>");
            sb.AppendLine("    {");
            sb.AppendLine($"        builder.OpenComponent<{c.Name}>(0);");
            sb.AppendLine("        var seq = 1;");
            sb.AppendLine("        foreach (var (key, value) in parameters)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (value is null) continue;");
            sb.AppendLine("            if (key == \"ChildContent\" && value is string text)");
            sb.AppendLine("                builder.AddAttribute(seq++, key, (RenderFragment)(b => b.AddContent(0, text)));");
            sb.AppendLine("            else");
            sb.AppendLine("                builder.AddAttribute(seq++, key, value);");
            sb.AppendLine("        }");
            sb.AppendLine("        builder.CloseComponent();");
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        // Type registry for DocGen reflection
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, System.Type> ComponentTypes = new Dictionary<string, System.Type>");
        sb.AppendLine("    {");
        foreach (var c in sorted)
        {
            sb.AppendLine($"        [\"{c.Name}\"] = typeof({c.Name}),");
        }
        sb.AppendLine("    };");

        sb.AppendLine("}");

        context.AddSource("PlaygroundFactories.g.cs", sb.ToString());
    }

    private static bool InheritsFrom(INamedTypeSymbol symbol, string baseName)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.Name == baseName)
                return true;
            current = current.BaseType;
        }
        return false;
    }

    private static bool HasRequiredCascadingParameter(INamedTypeSymbol symbol)
    {
        var current = (INamedTypeSymbol?)symbol;
        while (current is not null)
        {
            foreach (var member in current.GetMembers().OfType<IPropertySymbol>())
            {
                foreach (var attr in member.GetAttributes())
                {
                    if (attr.AttributeClass?.Name == "CascadingParameterAttribute")
                    {
                        if (member.Type.NullableAnnotation != NullableAnnotation.Annotated
                            && member.Type.Name != "Nullable")
                        {
                            return true;
                        }
                    }
                }
            }
            current = current.BaseType;
        }
        return false;
    }

    private static bool HasBrowsableFalse(INamedTypeSymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name == "BrowsableAttribute"
                && attr.ConstructorArguments.Length == 1
                && attr.ConstructorArguments[0].Value is false)
            {
                return true;
            }
        }
        return false;
    }

    private sealed class ComponentInfo
    {
        public string Name { get; }
        public string Namespace { get; }
        public string FullName { get; }

        public ComponentInfo(string name, string ns, string fullName)
        {
            Name = name;
            Namespace = ns;
            FullName = fullName;
        }
    }
}
