using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BlazingSpire.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class PlaygroundGenerator : IIncrementalGenerator
{
    private const string BaseClassName = "BlazingSpireComponentBase";
    private const string InfrastructureBaseName = "Infrastructure";
    private const string ChildOfBaseName = "ChildOf";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, GenerateSource);
    }

    private static void GenerateSource(SourceProductionContext context, Compilation compilation)
    {
        // ── Phase 1: Discover all concrete component types ──────────────────
        var allComponents = new Dictionary<string, ComponentInfo>();

        // ── Phase 1: Discover all concrete components ─────────────────────────
        // A component is included if it inherits BlazingSpireComponentBase but is NOT
        // an Infrastructure marker (providers, internal types).
        foreach (var tree in compilation.SyntaxTrees)
        {
            var model = compilation.GetSemanticModel(tree);
            foreach (var classDecl in tree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>())
            {
                if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
                    continue;
                if (symbol.IsAbstract || !symbol.CanBeReferencedByName || symbol.IsGenericType)
                    continue;
                if (!InheritsFrom(symbol, BaseClassName))
                    continue;
                if (HasBrowsableFalse(symbol))
                    continue;
                if (InheritsFrom(symbol, InfrastructureBaseName))
                    continue;

                var fullName = symbol.ToDisplayString();
                if (!allComponents.ContainsKey(fullName))
                    allComponents[fullName] = new ComponentInfo(symbol.Name, symbol.ContainingNamespace.ToDisplayString(), fullName, symbol);
            }
        }

        if (allComponents.Count == 0) return;

        // ── Phase 2: Find ChildOf<TParent> relationships ─────────────────────
        // A component is a Child if its base type is ChildOf<TParent>.
        // Pure type-system check — no attribute scanning, no naming heuristics.
        var parentToChildren = new Dictionary<string, List<ChildInfo>>();
        var childSet = new HashSet<string>();

        foreach (var comp in allComponents.Values)
        {
            var parentType = GetChildOfParent(comp.Symbol);
            if (parentType is null) continue;

            var parentFullName = parentType.ToDisplayString().TrimEnd('?');
            if (!allComponents.ContainsKey(parentFullName)) continue;

            var parentName = parentType.Name;
            var childName = comp.Name;
            var suffix = childName.StartsWith(parentName, StringComparison.Ordinal)
                ? childName.Substring(parentName.Length)
                : childName;
            if (string.IsNullOrEmpty(suffix)) suffix = childName;

            if (!parentToChildren.TryGetValue(parentFullName, out var children))
            {
                children = new List<ChildInfo>();
                parentToChildren[parentFullName] = children;
            }
            children.Add(new ChildInfo(comp.Name, suffix, comp.FullName));
            childSet.Add(comp.FullName);
        }

        // ── Phase 3: Top-level = not a child ────────────────────────────────
        var topLevel = allComponents.Values
            .Where(c => !childSet.Contains(c.FullName))
            .OrderBy(c => c.Name)
            .ToList();

        // ── Phase 4: Generate code ──────────────────────────────────────────
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// {allComponents.Count} total, {childSet.Count} children, {parentToChildren.Count} composites, {topLevel.Count} top-level");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Components;");
        sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        var allNamespaces = new HashSet<string>();
        foreach (var c in allComponents.Values) allNamespaces.Add(c.Namespace);
        foreach (var ns in allNamespaces.OrderBy(n => n))
            sb.AppendLine($"using {ns};");

        sb.AppendLine();
        sb.AppendLine("namespace BlazingSpire.Demo.Components.Demo;");
        sb.AppendLine();
        sb.AppendLine("public static class PlaygroundFactories");
        sb.AppendLine("{");

        // Registry: only top-level
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, System.Func<IReadOnlyDictionary<string, object?>, RenderFragment>> All = new Dictionary<string, System.Func<IReadOnlyDictionary<string, object?>, RenderFragment>>");
        sb.AppendLine("    {");
        foreach (var c in topLevel)
            sb.AppendLine($"        [\"{c.Name}\"] = Render{c.Name},");
        sb.AppendLine("    };");
        sb.AppendLine();

        // Factories
        foreach (var c in topLevel)
        {
            if (parentToChildren.TryGetValue(c.FullName, out var children))
                EmitCompositeFactory(sb, c, children);
            else
                EmitSimpleFactory(sb, c);
        }

        // Debug info
        // Debug: trace the Phase 2 logic for PopoverContent specifically
        var pcDebug = new List<string>();
        foreach (var tree in compilation.SyntaxTrees)
        {
            var treeModel = compilation.GetSemanticModel(tree);
            foreach (var propDecl in tree.GetRoot().DescendantNodes().OfType<PropertyDeclarationSyntax>())
            {
                var propAttrNames = propDecl.AttributeLists
                    .SelectMany(al => al.Attributes)
                    .Select(a => a.Name.ToString())
                    .ToList();
                if (!propAttrNames.Any(n => n.Contains("CascadingParameter"))) continue;

                var containingClass = propDecl.Ancestors().OfType<ClassDeclarationSyntax>().FirstOrDefault();
                var containingSymbol = containingClass is not null ? treeModel.GetDeclaredSymbol(containingClass) as INamedTypeSymbol : null;
                var propSymbol = treeModel.GetDeclaredSymbol(propDecl) as IPropertySymbol;
                var propTypeName = propSymbol?.Type?.ToDisplayString() ?? "null";
                var containingName = containingSymbol?.ToDisplayString() ?? "null";
                var isInAll = allComponents.ContainsKey(containingName);
                var parentInherits = propSymbol?.Type is INamedTypeSymbol pt ? InheritsFrom(pt, BaseClassName) : false;

                pcDebug.Add($"{containingSymbol?.Name}.{propDecl.Identifier}: type={propTypeName} inAll={isInAll} parentInherits={parentInherits}");
            }
        }
        var debugStr = string.Join(" | ", pcDebug.Take(10)).Replace("\"", "'");
        sb.AppendLine($"    public static readonly string DebugInfo = \"{allComponents.Count} total, {childSet.Count} children, {parentToChildren.Count} composites | {debugStr}\";");
        sb.AppendLine();
        // Type registry (all, for DocGen)
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, System.Type> ComponentTypes = new Dictionary<string, System.Type>");
        sb.AppendLine("    {");
        foreach (var c in allComponents.Values.OrderBy(x => x.Name))
            sb.AppendLine($"        [\"{c.Name}\"] = typeof({c.Name}),");
        sb.AppendLine("    };");

        sb.AppendLine("}");
        context.AddSource("PlaygroundFactories.g.cs", sb.ToString());
    }

    private static void EmitSimpleFactory(StringBuilder sb, ComponentInfo c)
    {
        sb.AppendLine($"    public static RenderFragment Render{c.Name}(IReadOnlyDictionary<string, object?> parameters) => builder =>");
        sb.AppendLine("    {");
        sb.AppendLine($"        builder.OpenComponent<{c.Name}>(0);");
        sb.AppendLine("        var seq = 1;");
        sb.AppendLine("        foreach (var (key, value) in parameters)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (value is null) continue;");
        sb.AppendLine("            if (key == \"ChildContent\" && value is string text)");
        sb.AppendLine("                builder.AddAttribute(seq++, key, (RenderFragment)(b => b.AddContent(0, text)));");
        sb.AppendLine("            else");
        sb.AppendLine("                builder.AddAttribute(seq++, key, value);");
        sb.AppendLine("        }");
        sb.AppendLine("        builder.CloseComponent();");
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static void EmitCompositeFactory(StringBuilder sb, ComponentInfo parent, List<ChildInfo> children)
    {
        var ordered = children.OrderBy(c => GetRoleOrder(c.Suffix)).ThenBy(c => c.Name).ToList();

        // Radix-style composites nest their body inside Content (e.g. Dialog/Title/Description/Action
        // are rendered inside DialogContent, not as siblings of it). When a Content child exists,
        // keep the Trigger at the parent's top level and nest everything else inside Content's
        // ChildContent. Content-like children only render when IsOpen, so rendering the body inside
        // avoids the bug where Title/Description/Action leak out and render next to the Trigger.
        var contentChild = ordered.FirstOrDefault(c => c.Suffix == "Content");
        var triggerChild = ordered.FirstOrDefault(c => c.Suffix == "Trigger");
        var innerChildren = contentChild is not null
            ? ordered.Where(c => c.Suffix != "Trigger" && c.Suffix != "Content").ToList()
            : new List<ChildInfo>();
        var topLevelChildren = contentChild is not null
            ? new List<ChildInfo> { triggerChild!, contentChild }.Where(c => c is not null).ToList()
            : ordered;

        sb.AppendLine($"    public static RenderFragment Render{parent.Name}(IReadOnlyDictionary<string, object?> parameters) => builder =>");
        sb.AppendLine("    {");
        sb.AppendLine($"        builder.OpenComponent<{parent.Name}>(0);");
        sb.AppendLine("        var seq = 1;");
        sb.AppendLine("        foreach (var (key, value) in parameters)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (value is null || key == \"ChildContent\") continue;");
        sb.AppendLine("            builder.AddAttribute(seq++, key, value);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(inner =>");
        sb.AppendLine("        {");
        sb.AppendLine("            #pragma warning disable CS0219");
        sb.AppendLine("            var childSeq = 0;");
        sb.AppendLine("            #pragma warning restore CS0219");

        foreach (var child in topLevelChildren)
        {
            if (child.Suffix is "Header" or "Footer" or "Group" or "List" or "Separator")
                continue;

            var defaultContent = GetDefaultContent(child.Suffix, parent.Name);
            if (defaultContent is null && child.Suffix != "Content") continue;

            sb.AppendLine($"            inner.OpenComponent<{child.Name}>(childSeq++);");

            if (child.Suffix == "Content" && innerChildren.Count > 0)
            {
                // Nest inner children (Title, Description, Action, Cancel, etc.) inside Content
                sb.AppendLine($"            inner.AddAttribute(childSeq++, \"ChildContent\", (RenderFragment)(body =>");
                sb.AppendLine("            {");
                sb.AppendLine("                #pragma warning disable CS0219");
                sb.AppendLine("                var bodySeq = 0;");
                sb.AppendLine("                #pragma warning restore CS0219");
                foreach (var bodyChild in innerChildren)
                {
                    if (bodyChild.Suffix is "Header" or "Footer" or "Group" or "List" or "Separator")
                        continue;
                    var bodyDefault = GetDefaultContent(bodyChild.Suffix, parent.Name);
                    if (bodyDefault is null) continue;
                    sb.AppendLine($"                body.OpenComponent<{bodyChild.Name}>(bodySeq++);");
                    if (!string.IsNullOrEmpty(bodyDefault))
                    {
                        var bodyEscaped = bodyDefault.Replace("\\", "\\\\").Replace("\"", "\\\"");
                        sb.AppendLine($"                body.AddAttribute(bodySeq++, \"ChildContent\", (RenderFragment)(cb => cb.AddContent(0, \"{bodyEscaped}\")));");
                    }
                    sb.AppendLine($"                body.CloseComponent();");
                }
                sb.AppendLine("            }));");
            }
            else if (!string.IsNullOrEmpty(defaultContent))
            {
                var escaped = defaultContent!.Replace("\\", "\\\\").Replace("\"", "\\\"");
                sb.AppendLine($"            inner.AddAttribute(childSeq++, \"ChildContent\", (RenderFragment)(cb => cb.AddContent(0, \"{escaped}\")));");
            }

            sb.AppendLine($"            inner.CloseComponent();");
        }

        sb.AppendLine("        }));");
        sb.AppendLine("        builder.CloseComponent();");
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static int GetRoleOrder(string suffix) => suffix switch
    {
        "Trigger" => 0, "Content" => 1, "Title" => 2, "Description" => 3,
        "Close" => 6, "Action" => 7, "Cancel" => 8, "Input" => 9,
        "Value" => 10, "Item" => 11, "Empty" => 12, "Label" => 13,
        _ => 50
    };

    private static string? GetDefaultContent(string suffix, string parentName) => suffix switch
    {
        "Trigger" => "Open " + parentName,
        "Content" => parentName + " content goes here.",
        "Title" => parentName,
        "Description" => "This is a " + parentName.ToLowerInvariant() + " description.",
        "Close" => "Close",
        "Action" => "Confirm",
        "Cancel" => "Cancel",
        "Item" => "Sample item",
        "Input" => "",
        "Value" => "Select...",
        "Empty" => "No results found.",
        "Label" => "Label",
        _ => null
    };

    private static bool InheritsFrom(INamedTypeSymbol symbol, string baseName)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.Name == baseName) return true;
            current = current.BaseType;
        }
        return false;
    }

    /// <summary>
    /// Returns the parent component type if this component inherits from <c>ChildOf&lt;TParent&gt;</c>,
    /// otherwise null. Walks the base class chain so subclasses of children also work.
    /// </summary>
    private static INamedTypeSymbol? GetChildOfParent(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.IsGenericType
                && current.Name == ChildOfBaseName
                && current.TypeArguments.Length == 1
                && current.TypeArguments[0] is INamedTypeSymbol parentType)
            {
                return parentType;
            }
            current = current.BaseType;
        }
        return null;
    }

    private static bool HasBrowsableFalse(INamedTypeSymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
            if (attr.AttributeClass?.Name == "BrowsableAttribute"
                && attr.ConstructorArguments.Length == 1
                && attr.ConstructorArguments[0].Value is false)
                return true;
        return false;
    }

    private sealed class ComponentInfo
    {
        public string Name { get; }
        public string Namespace { get; }
        public string FullName { get; }
        public INamedTypeSymbol Symbol { get; }
        public ComponentInfo(string name, string ns, string fullName, INamedTypeSymbol symbol)
        { Name = name; Namespace = ns; FullName = fullName; Symbol = symbol; }
    }

    private sealed class ChildInfo
    {
        public string Name { get; }
        public string Suffix { get; }
        public string FullName { get; }
        public ChildInfo(string name, string suffix, string fullName)
        { Name = name; Suffix = suffix; FullName = fullName; }
    }
}
