using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BlazingSpire.SourceGenerator;

/// <summary>
/// Builds the playground render factories purely from the type graph. The generator
/// walks <c>ChildOf&lt;TParent&gt;</c> inheritance chains bottom-up to build a composition
/// tree rooted at each top-level component, then emits nested render closures that
/// mirror the tree. Slot-like repeating children implement
/// <c>IRepeatingSlot&lt;TRoot&gt;</c>; the generator detects the interface and emits a
/// <c>for</c>-loop that invokes the static count method at render time against the live
/// root instance, so toggling parameters in the playground re-drives the loop.
///
/// <para>There are no suffix heuristics, no default-content maps, no attribute scans, and
/// no partial overrides. The composition <i>is</i> the type graph; the generator is a
/// dumb tree walker over it.</para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class PlaygroundGenerator : IIncrementalGenerator
{
    private const string BaseClassName = "BlazingSpireComponentBase";
    private const string InfrastructureBaseName = "Infrastructure";
    private const string ChildOfBaseName = "ChildOf";
    private const string RepeatingSlotInterfaceName = "IRepeatingSlot";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, GenerateSource);
    }

    private static void GenerateSource(SourceProductionContext context, Compilation compilation)
    {
        // ── Phase 1: Discover all concrete component types ──────────────────
        // A component is included if it inherits BlazingSpireComponentBase but is NOT
        // an Infrastructure marker (providers, internal types).
        var allComponents = new Dictionary<string, ComponentInfo>();
        foreach (var tree in compilation.SyntaxTrees)
        {
            var model = compilation.GetSemanticModel(tree);
            foreach (var classDecl in tree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>())
            {
                if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
                    continue;
                if (symbol.IsAbstract || !symbol.CanBeReferencedByName || symbol.IsGenericType)
                    continue;
                if (!InheritsFrom(symbol, BaseClassName))
                    continue;
                if (HasBrowsableFalse(symbol))
                    continue;
                if (InheritsFrom(symbol, InfrastructureBaseName))
                    continue;

                var fullName = symbol.ToDisplayString();
                if (!allComponents.ContainsKey(fullName))
                    allComponents[fullName] = new ComponentInfo(
                        symbol.Name, symbol.ContainingNamespace.ToDisplayString(), fullName, symbol);
            }
        }
        if (allComponents.Count == 0) return;

        // ── Phase 2: Build parent→children map from ChildOf<TParent> ─────────
        // Each child declares its IMMEDIATE visual parent. ChildOf is the sole signal.
        var parentToChildren = new Dictionary<string, List<ComponentInfo>>();
        var childSet = new HashSet<string>();

        foreach (var comp in allComponents.Values)
        {
            var parentType = GetChildOfParent(comp.Symbol);
            if (parentType is null) continue;

            var parentFullName = parentType.ToDisplayString().TrimEnd('?');
            if (!allComponents.ContainsKey(parentFullName)) continue;

            if (!parentToChildren.TryGetValue(parentFullName, out var list))
            {
                list = new List<ComponentInfo>();
                parentToChildren[parentFullName] = list;
            }
            list.Add(comp);
            childSet.Add(comp.FullName);
        }

        // Sort children at each level for deterministic emission.
        foreach (var kv in parentToChildren)
            kv.Value.Sort((a, b) => string.CompareOrdinal(a.Name, b.Name));

        // ── Phase 3: Top-level = a component that is not a ChildOf anything ─
        var topLevel = allComponents.Values
            .Where(c => !childSet.Contains(c.FullName))
            .OrderBy(c => c.Name)
            .ToList();

        // ── Phase 4: Generate code ──────────────────────────────────────────
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// {allComponents.Count} total, {childSet.Count} children, {parentToChildren.Count} composites, {topLevel.Count} top-level");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Components;");
        sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        var allNamespaces = new HashSet<string>();
        foreach (var c in allComponents.Values) allNamespaces.Add(c.Namespace);
        foreach (var ns in allNamespaces.OrderBy(n => n))
            sb.AppendLine($"using {ns};");

        sb.AppendLine();
        sb.AppendLine("namespace BlazingSpire.Demo.Components.Demo;");
        sb.AppendLine();
        sb.AppendLine("public static class PlaygroundFactories");
        sb.AppendLine("{");

        // Registry: only top-level components get a playground factory.
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, System.Func<IReadOnlyDictionary<string, object?>, RenderFragment>> All = new Dictionary<string, System.Func<IReadOnlyDictionary<string, object?>, RenderFragment>>");
        sb.AppendLine("    {");
        foreach (var c in topLevel)
            sb.AppendLine($"        [\"{c.Name}\"] = Render{c.Name},");
        sb.AppendLine("    };");
        sb.AppendLine();

        // Emit each top-level factory as a recursive tree walk over ChildOf.
        foreach (var root in topLevel)
            EmitRootFactory(sb, root, parentToChildren);

        // Type registry (all, for DocGen).
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, System.Type> ComponentTypes = new Dictionary<string, System.Type>");
        sb.AppendLine("    {");
        foreach (var c in allComponents.Values.OrderBy(x => x.Name))
            sb.AppendLine($"        [\"{c.Name}\"] = typeof({c.Name}),");
        sb.AppendLine("    };");

        sb.AppendLine("}");
        context.AddSource("PlaygroundFactories.g.cs", sb.ToString());
    }

    /// <summary>
    /// Emit <c>Render{Root.Name}</c> as a closed-generic RenderFragment factory. The root
    /// receives the playground parameter dict splat; descendants (emitted recursively)
    /// render with no user-controlled parameters beyond what their own IRepeatingSlot
    /// implementation supplies.
    /// </summary>
    private static void EmitRootFactory(StringBuilder sb, ComponentInfo root, Dictionary<string, List<ComponentInfo>> parentToChildren)
    {
        sb.AppendLine($"    public static RenderFragment Render{root.Name}(IReadOnlyDictionary<string, object?> parameters) => builder =>");
        sb.AppendLine("    {");
        sb.AppendLine($"        builder.OpenComponent<{root.Name}>(0);");
        sb.AppendLine("        var rootSeq = 1;");
        sb.AppendLine("        foreach (var (key, value) in parameters)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (value is null) continue;");
        sb.AppendLine("            if (key == \"ChildContent\" && value is string text)");
        sb.AppendLine("                builder.AddAttribute(rootSeq++, key, (RenderFragment)(b => b.AddContent(0, text)));");
        sb.AppendLine("            else if (key == \"ChildContent\")");
        sb.AppendLine("                continue;");
        sb.AppendLine("            else");
        sb.AppendLine("                builder.AddAttribute(rootSeq++, key, value);");
        sb.AppendLine("        }");

        // Capture the root as a typed local so IRepeatingSlot.GetSampleCount(root) calls
        // below can pass the live parent instance. The inner render lambda closes over
        // this array. Critical: Blazor's RenderTreeBuilder requires ALL AddAttribute calls
        // to come immediately after OpenComponent — AddComponentReferenceCapture must come
        // AFTER all attributes, otherwise the builder throws "Attributes may only be added
        // immediately after frames of type Element or Component".
        var hasChildren = parentToChildren.TryGetValue(root.FullName, out var rootChildren) && rootChildren.Count > 0;
        if (hasChildren)
        {
            sb.AppendLine($"        var rootRef = new {root.Name}[1];");

            // ChildContent attribute goes FIRST (while we're still in "attributes allowed" mode).
            sb.AppendLine("        builder.AddAttribute(rootSeq++, \"ChildContent\", (RenderFragment)(inner =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var seq0 = 0;");
            EmitChildrenList(sb, root, rootChildren!, parentToChildren, indent: "            ", builderVar: "inner", seqVar: "seq0", depth: 0);
            sb.AppendLine("        }));");

            // Then the reference capture. By render time the closure above hasn't fired yet;
            // Blazor processes the reference capture frame first (setting rootRef[0]) and
            // then invokes the ChildContent RenderFragment, which sees the populated array.
            sb.AppendLine($"        builder.AddComponentReferenceCapture(rootSeq++, inst => rootRef[0] = ({root.Name})inst);");
        }

        sb.AppendLine("        builder.CloseComponent();");
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    /// <summary>
    /// Recursively emits the children of a parent into the given builder variable. For
    /// each child, checks IRepeatingSlot: if present, emits a for-loop that calls the
    /// static GetSampleCount against the live root; otherwise emits a single instance
    /// and recurses into its own children.
    /// </summary>
    private static void EmitChildrenList(
        StringBuilder sb,
        ComponentInfo rootForRepeatLookup,
        List<ComponentInfo> children,
        Dictionary<string, List<ComponentInfo>> parentToChildren,
        string indent,
        string builderVar,
        string seqVar,
        int depth)
    {
        foreach (var child in children)
        {
            var repeating = GetRepeatingSlotRoot(child.Symbol);
            if (repeating is not null)
            {
                var rootTypeName = repeating.ToDisplayString().TrimEnd('?');
                var indexParam = GetRepeatingSlotIndexParameter(child.Symbol);
                // Emit a runtime for-loop driven by the static GetSampleCount.
                sb.AppendLine($"{indent}if (rootRef[0] is not null)");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    var count_{depth} = {child.Name}.GetSampleCount(rootRef[0]!);");
                sb.AppendLine($"{indent}    for (var i_{depth} = 0; i_{depth} < count_{depth}; i_{depth}++)");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        {builderVar}.OpenComponent<{child.Name}>({seqVar}++);");
                sb.AppendLine($"{indent}        {builderVar}.AddAttribute({seqVar}++, \"{indexParam}\", i_{depth});");
                EmitChildContentFragmentIfAny(sb, rootForRepeatLookup, child, parentToChildren,
                    indent + "        ", builderVar, seqVar, depth + 1);
                sb.AppendLine($"{indent}        {builderVar}.CloseComponent();");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine($"{indent}}}");
                continue;
            }

            // Single-instance child. Open, optionally recurse into its children, close.
            sb.AppendLine($"{indent}{builderVar}.OpenComponent<{child.Name}>({seqVar}++);");
            EmitChildContentFragmentIfAny(sb, rootForRepeatLookup, child, parentToChildren,
                indent, builderVar, seqVar, depth + 1);
            sb.AppendLine($"{indent}{builderVar}.CloseComponent();");
        }
    }

    /// <summary>
    /// If a child has grandchildren in the ChildOf graph, emit a ChildContent RenderFragment
    /// that recursively walks them. Otherwise no ChildContent is added — the child renders
    /// its own template with no user-supplied body.
    /// </summary>
    private static void EmitChildContentFragmentIfAny(
        StringBuilder sb,
        ComponentInfo rootForRepeatLookup,
        ComponentInfo child,
        Dictionary<string, List<ComponentInfo>> parentToChildren,
        string indent,
        string parentBuilderVar,
        string parentSeqVar,
        int depth)
    {
        if (!parentToChildren.TryGetValue(child.FullName, out var grand) || grand.Count == 0)
            return;

        var innerBuilderVar = $"b{depth}";
        var innerSeqVar = $"s{depth}";
        sb.AppendLine($"{indent}{parentBuilderVar}.AddAttribute({parentSeqVar}++, \"ChildContent\", (RenderFragment)({innerBuilderVar} =>");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var {innerSeqVar} = 0;");
        EmitChildrenList(sb, rootForRepeatLookup, grand, parentToChildren,
            indent + "    ", innerBuilderVar, innerSeqVar, depth);
        sb.AppendLine($"{indent}}}));");
    }

    // ── Type-graph helpers ──────────────────────────────────────────────────

    private static bool InheritsFrom(INamedTypeSymbol symbol, string baseName)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.Name == baseName) return true;
            current = current.BaseType;
        }
        return false;
    }

    /// <summary>
    /// Returns the parent component type if this component inherits from
    /// <c>ChildOf&lt;TParent&gt;</c>, otherwise null.
    /// </summary>
    private static INamedTypeSymbol? GetChildOfParent(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.IsGenericType
                && current.Name == ChildOfBaseName
                && current.TypeArguments.Length == 1
                && current.TypeArguments[0] is INamedTypeSymbol parentType)
            {
                return parentType;
            }
            current = current.BaseType;
        }
        return null;
    }

    /// <summary>
    /// Returns the <c>TRoot</c> type argument if the component implements
    /// <c>IRepeatingSlot&lt;TRoot&gt;</c>, otherwise null.
    /// </summary>
    private static INamedTypeSymbol? GetRepeatingSlotRoot(INamedTypeSymbol symbol)
    {
        foreach (var iface in symbol.AllInterfaces)
        {
            if (iface.Name == RepeatingSlotInterfaceName
                && iface.TypeArguments.Length == 1
                && iface.TypeArguments[0] is INamedTypeSymbol root)
            {
                return root;
            }
        }
        return null;
    }

    /// <summary>
    /// Returns the constant string returned by the component's
    /// <c>IRepeatingSlot&lt;TRoot&gt;.IndexParameterName</c> static property. Falls back
    /// to <c>"Index"</c> if the value can't be read at generation time (e.g. the property
    /// isn't a literal).
    /// </summary>
    private static string GetRepeatingSlotIndexParameter(INamedTypeSymbol symbol)
    {
        foreach (var member in symbol.GetMembers())
        {
            if (member is IPropertySymbol prop
                && prop.IsStatic
                && prop.Name == "IndexParameterName")
            {
                // Look for a property body that returns a literal string.
                foreach (var syntaxRef in prop.DeclaringSyntaxReferences)
                {
                    if (syntaxRef.GetSyntax() is PropertyDeclarationSyntax pds)
                    {
                        var literal = pds.ExpressionBody?.Expression as LiteralExpressionSyntax;
                        if (literal is not null && literal.Token.ValueText is string s)
                            return s;
                        // Also handle `=> nameof(SomeProperty);`
                        if (pds.ExpressionBody?.Expression is InvocationExpressionSyntax inv
                            && inv.Expression is IdentifierNameSyntax id
                            && id.Identifier.Text == "nameof"
                            && inv.ArgumentList.Arguments.Count == 1
                            && inv.ArgumentList.Arguments[0].Expression is IdentifierNameSyntax argId)
                        {
                            return argId.Identifier.Text;
                        }
                    }
                }
            }
        }
        return "Index";
    }

    private static bool HasBrowsableFalse(INamedTypeSymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
            if (attr.AttributeClass?.Name == "BrowsableAttribute"
                && attr.ConstructorArguments.Length == 1
                && attr.ConstructorArguments[0].Value is false)
                return true;
        return false;
    }

    private sealed class ComponentInfo
    {
        public string Name { get; }
        public string Namespace { get; }
        public string FullName { get; }
        public INamedTypeSymbol Symbol { get; }
        public ComponentInfo(string name, string ns, string fullName, INamedTypeSymbol symbol)
        { Name = name; Namespace = ns; FullName = fullName; Symbol = symbol; }
    }
}
